"""
In-memory confirmation token store for bill payment previews.

Tokens are generated by preview_bill_payment (via the MCP tool layer) and
consumed exactly once by create_bill_payment. They carry the full validated
payment payload so the execution step does not need to re-validate.

Token format: ``prev_{uuid4_hex[:12]}_{unix_timestamp}``
Example:      ``prev_a1b2c3d4e5f6_1744684800``

Note: The in-memory store is NOT thread-safe. This is fine for stdio
transport (single-threaded) but requires a threading.Lock if the MCP
server is run with SSE transport under concurrent requests.
"""

import threading
import time
import uuid
from typing import Any

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TOKEN_TTL: int = 300  # seconds (5 minutes)
TOKEN_PREFIX: str = "prev"

# ---------------------------------------------------------------------------
# In-memory store
# ---------------------------------------------------------------------------

_store: dict[str, dict[str, Any]] = {}

# Lock protecting all reads and writes to _store.
# Required because the FastAPI API layer dispatches tool calls via
# asyncio.to_thread(), meaning generate_token and consume_token can be
# called from worker threads concurrently.
_lock: threading.Lock = threading.Lock()

# ---------------------------------------------------------------------------
# Custom exceptions
# ---------------------------------------------------------------------------


class TokenExpiredError(Exception):
    """Raised when a token is found but its TTL has elapsed."""


class TokenAlreadyUsedError(Exception):
    """Raised when a token has already been consumed."""


class TokenNotFoundError(Exception):
    """Raised when the token string is not present in the store."""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_token(payment_payload: dict) -> str:
    """Mint a new confirmation token and store the payment payload.

    Args:
        payment_payload: Validated preview dict produced by
            ``qbo_client.preview_bill_payment``.

    Returns:
        Opaque token string in the format
        ``prev_{uuid4_hex[:12]}_{unix_timestamp}``.
    """
    now = time.time()
    token = f"{TOKEN_PREFIX}_{uuid.uuid4().hex[:12]}_{int(now)}"
    with _lock:
        _store[token] = {
            "payload": payment_payload,
            "expires_at": now + TOKEN_TTL,
            "used": False,
        }
    return token


def consume_token(token: str) -> dict:
    """Validate and consume a confirmation token, returning its payload.

    Marks the token as used on success so it cannot be replayed.

    Args:
        token: The confirmation token string returned by ``generate_token``.

    Returns:
        The payment payload dict that was stored when the token was generated.

    Raises:
        TokenNotFoundError: Token is not in the store.
        TokenExpiredError: Token TTL has elapsed.
        TokenAlreadyUsedError: Token was already consumed by a previous call.
    """
    with _lock:
        entry = _store.get(token)
        if entry is None:
            raise TokenNotFoundError(f"Token not found: {token}")

        if time.time() >= entry["expires_at"]:
            raise TokenExpiredError(f"Token expired: {token}")

        if entry["used"]:
            raise TokenAlreadyUsedError(f"Token already used: {token}")

        entry["used"] = True
        return entry["payload"]


def clear_store() -> None:
    """Remove all tokens from the in-memory store.

    Intended for use in tests only.
    """
    with _lock:
        _store.clear()
